### ISSUE TITLE
Alpine support dropeed?

### ISSUE THREAD

**Issue by gwitsch** [dokku/docker-image-labeler#166]
### Description of problem

docker-image-labeler cannot be run in an Alpine container anymore. Has the support been dropped?
Version 0.6.1 worked as expected.

### Steps to reproduce

```bash
# start container
docker run --rm -it --platform linux/amd64 alpine:3.20 /bin/sh

# install wget and download binary
apk add wget
wget https://github.com/dokku/docker-image-labeler/releases/download/v0.7.1/docker-image-labeler-linux-amd64

# make it executable
chmod a+x docker-image-labeler-linux-amd64

# run command
./docker-image-labeler-linux-amd64 --version
/bin/sh: ./docker-image-labeler-linux-amd64: not found

```

### docker-image-labeler version

# not working
v0.7.1
v0.7.0

# working
v0.6.1
v0.5.0

### Output of failing command

```shell
/bin/sh: ./docker-image-labeler-linux-amd64: not found
```

**Comment by josegonzalez** [comment]
Not sure why this is failing for you, but running that on my system works fine. I had to install gcompat though.

For the glibc/gcompat issue, maybe something [here](https://github.com/dokku/docker-image-labeler/blob/main/.github/workflows/tagged-release.yml#L38) (which builds the binaries for the release) doesn't match something [here](https://github.com/dokku/docker-image-labeler/blob/main/Makefile#L65) (which was the old release code)?

**Comment by gwitsch** [comment]
Thanks for pointing it out. Installing gcompat fixed my problem.
