### ISSUE TITLE
Question: setting creation date

### ISSUE THREAD

**Issue by gwitsch** [dokku/docker-image-labeler#63]
Hi,
is there a possibility to set the creation date for the newly created image? Or at least keep the original one?
Currently it's seems to be set to 1.1.1980

![updated image](https://user-images.githubusercontent.com/7790380/189074058-4604db2f-1375-4a41-8abf-91cbe4912ceb.jpg)

**Comment by gwitsch** [comment]
Ok, thanks for the clarification.
I will take a look at it and create a feature request.

**Comment by ismaail** [comment]
Hi, 

I'm facing this issue when I remove a label from an image,
is there any solution/workaround to keep the image date or set current date to the image ?

thanks.

**Comment by josegonzalez** [comment]
@ismaail I don't think so as the underlying library [still zeros out history](https://github.com/buildpacks/imgutil/blob/f8d38e1de03d30a169908d8b8a4c780a6081f23a/local/new.go#L193). You might consider making a change upstream to make that optional, in which case we could upgrade to that newer version and respect history dates.
