### ISSUE TITLE
There are issue with Dockerfile

### ISSUE THREAD

**Issue by pxorig** [dokku/docker-image-labeler#65]
### Description of problem

Thanks all contributors, this project help me quickly removes labels from docker images.
but I meet some problem when I building Dockerfile:
Error installing fpm
The last version of public_suffix (< 6.0, >= 2.0.2) to support your Ruby & RubyGems was 4.0.7. 
Try installing it with `gem install public_suffix -v 4.0.7` and then running the current command again.

### Steps to reproduce

sudo docker build -f Dockerfile -t docker-image-labeler .

### docker-image-labeler version

master

**Comment by josegonzalez** [comment]
This works for me now.
